<?php
/**
 * Created by PhpStorm.
 * User: mb
 * Date: 19.08.16
 * Time: 01:18
 */

namespace AnaN\Tree\Visitor\Node;


use AnaN\Tree\Interfaces\NodeInterface;
use AnaN\Tree\Visitor\AbstractVisitor;

abstract class AbstractNodeVisitor extends AbstractVisitor
{
	public function visit(NodeInterface $node):NodeInterface
	{
		return parent::visit($node); // TODO: Change the autogenerated stub
	}
}